safe:             true
auto:             true
server:           true
server_port:      7998
baseurl:          /Font-Awesome/311  # Where GitHub serves the project up from
url:              http://localhost:7998

source:           gh-pages/311
destination:      _gh_pages
plugins:          gh-pages/311/_plugins

pygments:         true

icon_meta:        gh-pages/311/icons.yml
icon_layout:      gh-pages/311/icon.html    # Relative to _layouts directory
icon_destination: gh-pages/311/icon         # Relative to destination

font_awesome:
  version:        3.1.1
  url:            http://veliovgroup.github.com
  legacy_url:     http://veliovgroup.github.com/Font-Awesome/311
  twitter:        fontawesome
  author:
    name:         Dave Gandy
    email:        dave@fontawesome.io
    twitter:      byscuits
  github:
    url:          https://github.com/FortAwesome/Font-Awesome
    project:      Font-Awesome
    org:          FortAwesome
  icon_count:     302
  new_icon_count: 54

bootstrap:
  version:        2.3.1
  url:            http://bootstrap-ru.com

license:
  font:
    version:      SIL OFL 1.1
    url:          http://scripts.sil.org/OFL
  code:
    version:      MIT License
    url:          http://opensource.org/licenses/mit-license.html
  documentation:
    version:      CC BY 3.0
    url:          http://creativecommons.org/licenses/by/3.0/
